echo "Setting up environment..."
config_path="$HOME/.bashrc"
workspace_repo_dir="/workspace/learn-spring"
brew_home="/home/linuxbrew/.linuxbrew"
echo "Finished setting up environment:"
echo "  config_path: ${config_path}"
echo "  workspace_repo_dir: ${workspace_repo_dir}"
echo "  brew_home: ${brew_home}"
echo "-------------------------------------------------------------------"
echo ""
